name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-weekly  # ← CORRECT IMAGE NAME
      options: --user root

    steps:
      - name: Run ZAP Baseline Scan
        run: |
          zap-baseline.py \
          -t ${{ vars.TARGET_URL || 'http://localhost:8080' }} \
          -r zap-report.html \
          -x zap-report.xml \
          -J zap-report.json \
          -d

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.xml
            zap-report.json

      - name: Check Results
        run: |
          if grep -q "<riskcode>3" zap-report.xml; then
            echo "::error::High risk vulnerabilities detected!"
            exit 1
          fi
